# ----------------------------
# Makefile Options
# ----------------------------

NAME = RickROLL
ICON = icon.png
DESCRIPTION = "Read the Title,Dingus"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
